development:
  password: shptka_5933c2fa9d334fb072a19a793525a8c4
  theme_id: "140441125180"
  store: saad-test-ecomexperts.myshopify.com
  ignore_files:
    - README.md
    - gulpfile.js
    - node_modules/*
    - package.json
    - package-lock.json